name: Deploy student connect pages server

on:
  workflow_dispatch:
  push:
    branches:
      - question

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Navigate to the backend directory
      - name: Navigate to backend directory
        run: cd student-connect/server

      # Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Build the project
      - name: Build project
        run: node app.js