name: Deploy StudentConnect

on:
  push:
    branches:
      - 'main'
      - 'gcloud-test'
  pull_request:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Gcloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker images
        run: |
          docker compose build
          docker tag 
          docker push us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/student-connect:latest


